CREATE FUNCTION [SCH_Aptude_KBX].[FN_Encrypt]
(
	@NoEncriptado VARCHAR(50)
)

RETURNS VARBINARY(MAX)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @phrase VARCHAR(50)
	SET @phrase = 'NO ES QUE MUERA DE AMOR'

	RETURN ENCRYPTBYPASSPHRASE (@phrase, @NoEncriptado )
END